#pragma config(Sensor, S4,     HTANG_LEFT,     sensorI2CCustom)
#pragma config(Sensor, S1,     HTANG_RIGHT,    sensorI2CCustom)
#pragma config(Motor,  motorC,          MOTOR_LEFT,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorA,          MOTOR_RIGHT,   tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(NXT)



//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: ROBOTC PROJECT MAIN FILE DECLARATION
#ifndef PROJECT_MAIN_FILE
#define PROJECT_MAIN_FILE "main.c" //!< enable compilation of task main() and various debug and test functions of this file
#endif
// END OF:  ROBOTC PROJECT MAIN FILE DECLARATION
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: HEADERS
// END OF:  HEADERS
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: GLOBAL INSTANCES
// END OF:  GLOBAL INSTANCES
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: EXTERNAL SOURCES
#include "crobotTrajWrappers.c"
// END OF:  EXTERNAL SOURCES
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: LOCAL INSTANCES
// END OF:  LOCAL INSTANCES
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: CODES

#define GRAPH_PID 1

#if(PROJECT_MAIN_FILE == "main.c")


task main()
//task testSubtask()
{

	//Display NXT
	nxtDisplayCenteredTextLine(0, "PMX robot-test");
	nxtDisplayCenteredBigTextLine(1, "MOTOR");
	nxtDisplayCenteredTextLine(3, "pmSquareTest");
	writeDebugStreamLine("PMX robot-test | MOTOR | pmSquareTest");

	//float dist = 1.000; // in meters
	float x1, y1, theta1;
	TRAJ_STATE ts;

	motion_Init();




		pid_ConfigKP(motors[ALPHA_DELTA][ALPHA_MOTOR].PIDSys, 800);
		pid_ConfigKI(motors[ALPHA_DELTA][ALPHA_MOTOR].PIDSys, 0);
		pid_ConfigKD(motors[ALPHA_DELTA][ALPHA_MOTOR].PIDSys, 400);
		pid_ConfigDPeriod(motors[ALPHA_DELTA][ALPHA_MOTOR].PIDSys, 3);
		pid_ConfigKP(motors[ALPHA_DELTA][DELTA_MOTOR].PIDSys, 500);
		pid_ConfigKI(motors[ALPHA_DELTA][DELTA_MOTOR].PIDSys, 0);
		pid_ConfigKD(motors[ALPHA_DELTA][DELTA_MOTOR].PIDSys, 500);
		pid_ConfigDPeriod(motors[ALPHA_DELTA][DELTA_MOTOR].PIDSys, 3);

		pid_ConfigKP(motors[LEFT_RIGHT][LEFT_MOTOR].PIDSys, 75);
		pid_ConfigKI(motors[LEFT_RIGHT][LEFT_MOTOR].PIDSys, 0);
		pid_ConfigKD(motors[LEFT_RIGHT][LEFT_MOTOR].PIDSys, 50);
		pid_ConfigKP(motors[LEFT_RIGHT][RIGHT_MOTOR].PIDSys, 75);
		pid_ConfigKI(motors[LEFT_RIGHT][RIGHT_MOTOR].PIDSys, 5);
		pid_ConfigKD(motors[LEFT_RIGHT][RIGHT_MOTOR].PIDSys, 50);
		motors_ConfigAllIMax(90000);

  ts = motion_DoLine(-0.10);

	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);
/*
	ts = motion_DoRotate(PI/2.0);

	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);

	ts = motion_DoLine(-0.10);

	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);

	ts = motion_DoRotate(PI/2.0);

	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);

	ts = motion_DoLine(-0.10);

	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);

	ts = motion_DoRotate(PI/2.0);

	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);

	ts = motion_DoLine(-0.10);

	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);

	ts = motion_DoRotate(PI/2.0);

	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);
*/




	ts = motion_DoRotate(PI / 2.0);
	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);
/*
	ts = motion_DoRotate(-(PI / 2.0));
	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);

	ts = motion_DoRotate(PI/2.0);
	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);

	ts = motion_DoRotate(-PI/2.0);
	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);

	ts = motion_DoRotate(PI/2.0);
	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);

	ts = motion_DoRotate(-PI/2.0);
	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);

	ts = motion_DoRotate(PI/2.0);
	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);

	ts = motion_DoRotate(-PI/2.0);
	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x=%f  y=%f  theta=%f",x1, y1, theta1);
*/



	Sleep(1000);
	odo_GetPositionXYTheta(&x1, &y1, &theta1);
	writeDebugStreamLine("x1=%f  y1=%f  theta1=%f",x1, y1, theta1);
	writeDebugStreamLine("pmSquareTest.c : END OF PMX !!!!");

	motion_StopTimer();
}

/*
task main()
{
	motion_Init();
	StartTask(testSubtask, 5);
  wait1Msec(90000);
}
*/
// END OF:  CODES
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#endif
