#!/bin/bash

#IP="192.168.7.251"
IP="192.168.2.110"


view_doc()
{
    firefox doc/html/index.html >/dev/null 2>&1 &
}

all()
{
	scp src/apf-test/sh/*.sh PMXArmadeusBinaries/* root@$IP:/pmx/
}

conf()
{
	scp PMXArmadeusBinaries/*.conf.txt root@$IP:/pmx/
}

tsh()
{
	scp src/apf-test/sh/*.sh root@$IP:/pmx/
}

robottest()
{
	scp PMXArmadeusBinaries/ROBOT_TEST root@$IP:/pmx/
}

pmx()
{
    ssh root@$IP "killall pmx"
	scp "PMXArmadeusBinaries/PMX" root@$IP:/pmx/
}

devtest()
{
	scp PMXArmadeusBinaries/DEV_TEST root@$IP:/pmx/
}

apftest()
{
	scp PMXArmadeusBinaries/APF_TEST root@$IP:/pmx/
}

recupcsvhost()
{
    #recup sur le PC Host
	scp root@$IP:/pmx/*.* /mnt/hgfs/pmx_xls/
}

recupcsv()
{
        scp root@$IP:/pmx/*.* /home/pmx/Arecup/.
}

recupsvg()
{
        scp root@$IP:/pmx/*.svg /home/pmx/workspace/ARM/SVG/.
}

connect()
{
	ssh root@$IP
}

case "$1" in
	view-doc)
		view_doc
	;;

	all)
		all
	;;

	conf)
		conf
	;;

	tsh)
		tsh
	;;

	pmx)
		pmx
	;;
	
        robottest)
		robottest
	;;

	
        apftest)
		apftest
	;;

	devtest)
		devtest
	;;

	connect)
		connect
	;;
        
        recupcsv)
		recupcsv
	;;

        recupsvg)
		recupsvg
	;;

        recupcsvhost)
		recupcsvhost
	;;

	*)
		echo "Usage: $0 {connect|pmx|devtest|robottest|apftest|all|conf|tsh|view-doc|recupcsv|recupsvg|recupcsvhost}" >&2
		exit 1
	;;
esac

exit 0
