#pragma config(Sensor, S4,     HTANG_LEFT,     sensorI2CCustom)
#pragma config(Sensor, S1,     HTANG_RIGHT,    sensorI2CCustom)
#pragma config(Motor,  motorC,          MOTOR_LEFT,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorA,          MOTOR_RIGHT,   tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(NXT)

#ifndef _PID
#define _PID // prevent multiple compilations

//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: ROBOTC PROJECT MAIN FILE DECLARATION
#ifndef PROJECT_MAIN_FILE
#define PROJECT_MAIN_FILE "cpid.c" //!< enable compilation of task main() and various debug and test functions of this file
#endif
// END OF:  ROBOTC PROJECT MAIN FILE DECLARATION
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: HEADERS
#ifndef _CONFIG_H_
#include "cconfig.h"
#endif
#ifndef _PID_H_
#include "cpid.h"
#endif
// END OF:  HEADERS
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: GLOBAL INSTANCES
//number of system created so far
PID_SYSTEM pid_Nb;
// END OF:  GLOBAL INSTANCES
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: EXTERNAL SOURCES
// END OF:  EXTERNAL SOURCES
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: LOCAL INSTANCES
// END OF:  LOCAL INSTANCES
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: CODES

//! \brief Get the current configuration of the PID system
//!
//! \param system The system
//! \return The current configuration of the system
void pid_GetConfig(pidConfig &pidConfig, PID_SYSTEM system)
{
	pidConfig = systemValues[system].conf;
}


//! \brief Compute the PID sum of a system
//!
//! \param system The system on which we compute the PID
//! \param error The difference between measured and reference values in ticks/sample
//! \param vitesse The vitesse in vTops/sample
//! \return The new command to apply on the system (pwm)
long pid_ComputeRcva(PID_SYSTEM system, long error, long vitesse)
{
	//http://www.rcva.fr/index.php?option=com_content&view=article&id=27&Itemid=42&limitstart=8
	/*
	commande = ecart * GAIN_PROPORTIONNEL_DISTANCE
	commande_distance = commande – GAIN_DERIVE_DISTANCE*vitesse
	commande_roue_D= commande_distance
	commande_roue_G= commande_distance
	*/
	pidSystemValues *val;
	val = &(systemValues[system]);

	#if(LEVEL_PID <= DEBUG)
		writeDebugStreamLine("cpid.c : before error=%d vitesse=%d", error, vitesse);
	#endif

	error /= VTOPS_PER_TICKS; //=[Ticks/sample]
	vitesse /= VTOPS_PER_TICKS; //=[Ticks/sample]

	long cmd = error * val->conf.kP;
	long pwm = cmd - val->conf.kD * vitesse;

	#if(LEVEL_PID <= DEBUG)
		writeDebugStreamLine("cpid.c : during error=%d vitesse=%d pwm=%d", error, vitesse, pwm);
	#endif

	pwm /= 256; //2048 ou 1024 ou 256??

	#if(LEVEL_PID <= DEBUG)
		writeDebugStreamLine("cpid.c : after  error=%d vitesse=%d pwm=%d", error, vitesse, pwm);
	#endif

	//bound the resulting pwm
	if(pwm > MAX_PWM_VALUE)
	{
		pwm = MAX_PWM_VALUE;
	}
	else if(pwm < -MAX_PWM_VALUE)
	{
		pwm = -MAX_PWM_VALUE;
	}

	return pwm;
}

//! \brief Compute the PID sum of a system
//!
//! \param system The system on which we compute the PID
//! \param error The difference between measured and reference values in ticks
//! \return The new command to apply on the system (pwm)

long pid_Compute(PID_SYSTEM system, long error)
{
	#if(LEVEL_PID <= DEBUG)
		writeDebugStreamLine("cpid.c : dbu error=%d", error);
	#endif


	pidSystemValues *val;
	long P,I,D;
	long pwm;
	long errDif;
	int last;

	error /= VTOPS_PER_TICKS;

	val = &(systemValues[system]);

	//stock last values of the error, so we can
	//differentiate over a custom period
	val->curDiff++;
	if(val->curDiff >= MAX_D_PERIOD)
	{
		val->curDiff = 0; //restart at the beginning of the buffer
	}

	//modif test :
	//sum of all errors of the MAX_D_PERIOD previous period
	val->errSum -= val->dValues[val->curDiff];
	val->errSum += error;

	//bound integration values //!! TODO CCH Don't seem to work
	if(val->errSum > val->conf.iMax)
	{
		val->errSum = val->conf.iMax;
		//signalErrorOverflow(system);
	}
	else if(val->errSum < -val->conf.iMax)
	{
		val->errSum = -val->conf.iMax;
		//signalErrorOverflow(system);
	}

	//fill the rotating buffer
	val->dValues[val->curDiff] = error;

	//if we are at the begining of the rotating buffer
	//we have to take a value at the end of it
	if(val->conf.dPeriod > val->curDiff)
	{
		last = MAX_D_PERIOD + val->curDiff - val->conf.dPeriod;
	}
	else
	{
		last = val->curDiff - val->conf.dPeriod;
	}

	//differential of the error over the period
	errDif = error - val->dValues[last];

	#if(LEVEL_PID <= DEBUG)
		writeDebugStreamLine("cpid.c : end error=%d  val->errSum=%d errDif=%d iMax=%d", error, val->errSum, errDif, val->conf.iMax);
	#endif

	P = error * val->conf.kP;
	I = val->errSum * val->conf.kI;
	D = errDif * val->conf.kD;

	pwm = P + I + D;

	pwm /= 256;

	//bound the resulting pwm
	if(pwm > MAX_PWM_VALUE)
	{
		pwm = MAX_PWM_VALUE;
	}
	else if(pwm < -MAX_PWM_VALUE)
	{
		pwm = -MAX_PWM_VALUE;
	}

	return pwm;
}

//! \brief Reset the integral error
//!
//! When for example the power supply of the motors is shut down,
//! the pid accumulate error (integral term), if the power is
//! set up again after a while, the motor will try to correct
//! abruptly this error. To avoid this problem, we provide the
//! following function to reset the integral of the error and
//! all previous error for differential.
//! \param system The system that will be reseted
void pid_ResetError(PID_SYSTEM system)
{
	int i;

	for(i=0; i<MAX_D_PERIOD; i++)
		systemValues[pid_Nb].dValues[i] = 0;

	systemValues[pid_Nb].errSum = 0;
	systemValues[pid_Nb].curDiff = 0;
}

void pid_Init()
{
	pid_Nb = 0;
	//REGISTER_LOG_CLIENT("PID");
}

PID_SYSTEM pid_Create()
{
	//no more available system
	if(pid_Nb >= MAX_PID_SYSTEM_NUMBER)
		return -1;

	//init configuration variables
	systemValues[pid_Nb].conf.kP = 0;
	systemValues[pid_Nb].conf.kI = 0;
	systemValues[pid_Nb].conf.kD = 0;
	systemValues[pid_Nb].conf.dPeriod = 1;
	systemValues[pid_Nb].conf.iMax = 128000;
	systemValues[pid_Nb].curDiff = 0;

	//init current state variables
	pid_ResetError(pid_Nb);

	pid_Nb++;
	return pid_Nb-1;
}


//TODO
//! \brief This function signal a very big error integral value,
//! generally it is caused by a hardware problem
//void signalErrorOverflow(PID_SYSTEM system)
//{
//	if(getMotorSpeed(&(motors[ALPHA_DELTA][DELTA_MOTOR])) > 0)
//	{
//		collision_SignalShock(FRONT_SHOCK);
//		LOG_ERROR1("PID Overflow'd front : %d", system);
//	}
//	else
//	{
//		collision_SignalShock(BACK_SHOCK);
//		LOG_ERROR1("PID Overflow'd back : %d", system);
//	}
//}

void pid_Configure(PID_SYSTEM system, pidConfig config)
{
	systemValues[system].conf = config;
}

void pid_ConfigKP(PID_SYSTEM system, long kp)
{
	systemValues[system].conf.kP = kp;
}
void pid_ConfigKI(PID_SYSTEM system, long ki)
{
	systemValues[system].conf.kI = ki;
}
void pid_ConfigKD(PID_SYSTEM system, long kd)
{
	systemValues[system].conf.kD = kd;
}
void pid_ConfigDPeriod(PID_SYSTEM system, int dperiod)
{
	systemValues[system].conf.dPeriod = dperiod;
}
void pid_ConfigIMax(PID_SYSTEM system, long imax)
{
	systemValues[system].conf.iMax = imax;
}

// END OF:  CODES
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

//<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
// SECTION: TESTS

#if(PROJECT_MAIN_FILE == "cpid.c")
	//-----------------------------------------------------------------------------------------------------------------------------
	//! @brief     this task tests the functions
	//! @return    none
	//! @author    cho
	//! @note
	//! @todo
	//-----------------------------------------------------------------------------------------------------------------------------
	task main()
	{
		pid_Init();

	}
#endif // (PROJECT_MAIN_FILE)

// END OF:  TESTS
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

#endif
